/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pages;

import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author Alice Ochoa
 */
public class MenuV2 extends javax.swing.JFrame {

    /**
     * Creates new form MenuV2
     */
    public MenuV2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraLateral = new javax.swing.JPanel();
        buttonHome = new javax.swing.JPanel();
        yellowBar = new javax.swing.JPanel();
        iconHome = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        buttonAnalytics = new javax.swing.JPanel();
        yellowBar2 = new javax.swing.JPanel();
        iconAnalytics = new javax.swing.JLabel();
        analytics = new javax.swing.JLabel();
        buttonScrum = new javax.swing.JPanel();
        yellowBar4 = new javax.swing.JPanel();
        iconScrum = new javax.swing.JLabel();
        scrum = new javax.swing.JLabel();
        buttonTdS = new javax.swing.JPanel();
        yellowBar5 = new javax.swing.JPanel();
        iconTdS = new javax.swing.JLabel();
        testesDeSoftware = new javax.swing.JLabel();
        buttonAngular = new javax.swing.JPanel();
        yellowBar7 = new javax.swing.JPanel();
        iconAngular = new javax.swing.JLabel();
        angular = new javax.swing.JLabel();
        fundoAngular = new javax.swing.JPanel();
        temas = new javax.swing.JPanel();
        tema6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        retorno6 = new javax.swing.JLabel();
        tema5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        retorno5 = new javax.swing.JLabel();
        tema4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        retorno4 = new javax.swing.JLabel();
        tema3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        retorno3 = new javax.swing.JLabel();
        tema2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        retorno2 = new javax.swing.JLabel();
        tema1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        retorno1 = new javax.swing.JLabel();
        fundoAngular2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fundoTdS = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        botaoTema1 = new javax.swing.JLabel();
        botaoTema2 = new javax.swing.JLabel();
        botaoTema3 = new javax.swing.JLabel();
        botaoTema4 = new javax.swing.JLabel();
        botaoTema5 = new javax.swing.JLabel();
        botaoTema6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fundoScrum = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fundoAnalytics = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fundoHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 100, 100));
        setResizable(false);

        barraLateral.setBackground(new java.awt.Color(25, 28, 53));

        buttonHome.setBackground(new java.awt.Color(33, 45, 73));
        buttonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHomeMouseClicked(evt);
            }
        });

        yellowBar.setBackground(new java.awt.Color(237, 193, 49));

        javax.swing.GroupLayout yellowBarLayout = new javax.swing.GroupLayout(yellowBar);
        yellowBar.setLayout(yellowBarLayout);
        yellowBarLayout.setHorizontalGroup(
            yellowBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        yellowBarLayout.setVerticalGroup(
            yellowBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/home_page_24px.png"))); // NOI18N

        home.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        home.setForeground(new java.awt.Color(231, 231, 231));
        home.setText("Página Inicial");

        javax.swing.GroupLayout buttonHomeLayout = new javax.swing.GroupLayout(buttonHome);
        buttonHome.setLayout(buttonHomeLayout);
        buttonHomeLayout.setHorizontalGroup(
            buttonHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonHomeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(yellowBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iconHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        buttonHomeLayout.setVerticalGroup(
            buttonHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(iconHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(yellowBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        buttonAnalytics.setBackground(new java.awt.Color(33, 45, 73));
        buttonAnalytics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAnalyticsMouseClicked(evt);
            }
        });

        yellowBar2.setBackground(new java.awt.Color(237, 193, 49));

        javax.swing.GroupLayout yellowBar2Layout = new javax.swing.GroupLayout(yellowBar2);
        yellowBar2.setLayout(yellowBar2Layout);
        yellowBar2Layout.setHorizontalGroup(
            yellowBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        yellowBar2Layout.setVerticalGroup(
            yellowBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconAnalytics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/increase_24px.png"))); // NOI18N

        analytics.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        analytics.setForeground(new java.awt.Color(231, 231, 231));
        analytics.setText("Analytics");

        javax.swing.GroupLayout buttonAnalyticsLayout = new javax.swing.GroupLayout(buttonAnalytics);
        buttonAnalytics.setLayout(buttonAnalyticsLayout);
        buttonAnalyticsLayout.setHorizontalGroup(
            buttonAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonAnalyticsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(yellowBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iconAnalytics)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(analytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        buttonAnalyticsLayout.setVerticalGroup(
            buttonAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonAnalyticsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(analytics, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(iconAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(yellowBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        buttonScrum.setBackground(new java.awt.Color(33, 45, 73));
        buttonScrum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonScrumMouseClicked(evt);
            }
        });

        yellowBar4.setBackground(new java.awt.Color(237, 193, 49));

        javax.swing.GroupLayout yellowBar4Layout = new javax.swing.GroupLayout(yellowBar4);
        yellowBar4.setLayout(yellowBar4Layout);
        yellowBar4Layout.setHorizontalGroup(
            yellowBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        yellowBar4Layout.setVerticalGroup(
            yellowBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconScrum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/event_24px.png"))); // NOI18N

        scrum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        scrum.setForeground(new java.awt.Color(231, 231, 231));
        scrum.setText("Scrum");

        javax.swing.GroupLayout buttonScrumLayout = new javax.swing.GroupLayout(buttonScrum);
        buttonScrum.setLayout(buttonScrumLayout);
        buttonScrumLayout.setHorizontalGroup(
            buttonScrumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonScrumLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(yellowBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iconScrum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        buttonScrumLayout.setVerticalGroup(
            buttonScrumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonScrumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonScrumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrum, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(iconScrum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(yellowBar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        buttonTdS.setBackground(new java.awt.Color(33, 45, 73));
        buttonTdS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTdSMouseClicked(evt);
            }
        });

        yellowBar5.setBackground(new java.awt.Color(237, 193, 49));

        javax.swing.GroupLayout yellowBar5Layout = new javax.swing.GroupLayout(yellowBar5);
        yellowBar5.setLayout(yellowBar5Layout);
        yellowBar5Layout.setHorizontalGroup(
            yellowBar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        yellowBar5Layout.setVerticalGroup(
            yellowBar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconTdS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/pass_fail_24px.png"))); // NOI18N

        testesDeSoftware.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        testesDeSoftware.setForeground(new java.awt.Color(231, 231, 231));
        testesDeSoftware.setText("Testes de Software");

        javax.swing.GroupLayout buttonTdSLayout = new javax.swing.GroupLayout(buttonTdS);
        buttonTdS.setLayout(buttonTdSLayout);
        buttonTdSLayout.setHorizontalGroup(
            buttonTdSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonTdSLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(yellowBar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iconTdS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(testesDeSoftware, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        buttonTdSLayout.setVerticalGroup(
            buttonTdSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonTdSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonTdSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testesDeSoftware, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(iconTdS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(yellowBar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        buttonAngular.setBackground(new java.awt.Color(33, 45, 73));
        buttonAngular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAngularMouseClicked(evt);
            }
        });

        yellowBar7.setBackground(new java.awt.Color(237, 193, 49));

        javax.swing.GroupLayout yellowBar7Layout = new javax.swing.GroupLayout(yellowBar7);
        yellowBar7.setLayout(yellowBar7Layout);
        yellowBar7Layout.setHorizontalGroup(
            yellowBar7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        yellowBar7Layout.setVerticalGroup(
            yellowBar7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconAngular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/google_code_24px.png"))); // NOI18N

        angular.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        angular.setForeground(new java.awt.Color(231, 231, 231));
        angular.setText("Angular");

        javax.swing.GroupLayout buttonAngularLayout = new javax.swing.GroupLayout(buttonAngular);
        buttonAngular.setLayout(buttonAngularLayout);
        buttonAngularLayout.setHorizontalGroup(
            buttonAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonAngularLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(yellowBar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iconAngular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(angular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        buttonAngularLayout.setVerticalGroup(
            buttonAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonAngularLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(angular, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(iconAngular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(yellowBar7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barraLateralLayout = new javax.swing.GroupLayout(barraLateral);
        barraLateral.setLayout(barraLateralLayout);
        barraLateralLayout.setHorizontalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonScrum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonTdS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonAngular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        barraLateralLayout.setVerticalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(buttonHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonScrum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTdS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAngular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        fundoAngular.setBackground(new java.awt.Color(0, 255, 255));

        temas.setBackground(new java.awt.Color(231, 231, 231));

        tema6.setBackground(new java.awt.Color(231, 231, 231));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/pagtema6.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/resumodotema.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        retorno6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/retornarpag.png"))); // NOI18N
        retorno6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retorno6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tema6Layout = new javax.swing.GroupLayout(tema6);
        tema6.setLayout(tema6Layout);
        tema6Layout.setHorizontalGroup(
            tema6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(tema6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addContainerGap(267, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tema6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retorno6)
                .addGap(34, 34, 34))
        );
        tema6Layout.setVerticalGroup(
            tema6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(retorno6)
                .addGap(30, 30, 30))
        );

        tema5.setBackground(new java.awt.Color(231, 231, 231));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/pagtema5.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/resumodotema.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        retorno5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/retornarpag.png"))); // NOI18N
        retorno5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retorno5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tema5Layout = new javax.swing.GroupLayout(tema5);
        tema5.setLayout(tema5Layout);
        tema5Layout.setHorizontalGroup(
            tema5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(tema5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tema5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retorno5)
                .addGap(34, 34, 34))
        );
        tema5Layout.setVerticalGroup(
            tema5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(retorno5)
                .addGap(30, 30, 30))
        );

        tema4.setBackground(new java.awt.Color(231, 231, 231));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/pagtema4.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/resumodotema.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        retorno4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/retornarpag.png"))); // NOI18N
        retorno4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retorno4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tema4Layout = new javax.swing.GroupLayout(tema4);
        tema4.setLayout(tema4Layout);
        tema4Layout.setHorizontalGroup(
            tema4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(tema4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tema4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retorno4)
                .addGap(34, 34, 34))
        );
        tema4Layout.setVerticalGroup(
            tema4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(50, 50, 50)
                .addComponent(retorno4)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tema3.setBackground(new java.awt.Color(231, 231, 231));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/pagtema3.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/resumodotema.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        retorno3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/retornarpag.png"))); // NOI18N
        retorno3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retorno3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tema3Layout = new javax.swing.GroupLayout(tema3);
        tema3.setLayout(tema3Layout);
        tema3Layout.setHorizontalGroup(
            tema3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(tema3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tema3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retorno3)
                .addGap(34, 34, 34))
        );
        tema3Layout.setVerticalGroup(
            tema3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(retorno3)
                .addGap(30, 30, 30))
        );

        tema2.setBackground(new java.awt.Color(231, 231, 231));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/pagtema2.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/resumodotema.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        retorno2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/retornarpag.png"))); // NOI18N
        retorno2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retorno2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tema2Layout = new javax.swing.GroupLayout(tema2);
        tema2.setLayout(tema2Layout);
        tema2Layout.setHorizontalGroup(
            tema2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(tema2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tema2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retorno2)
                .addGap(34, 34, 34))
        );
        tema2Layout.setVerticalGroup(
            tema2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(retorno2)
                .addGap(30, 30, 30))
        );

        tema1.setBackground(new java.awt.Color(231, 231, 231));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/pagtema1.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/resumodotema.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        retorno1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/retornarpag.png"))); // NOI18N
        retorno1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retorno1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tema1Layout = new javax.swing.GroupLayout(tema1);
        tema1.setLayout(tema1Layout);
        tema1Layout.setHorizontalGroup(
            tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tema1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retorno1)
                .addGap(34, 34, 34))
        );
        tema1Layout.setVerticalGroup(
            tema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tema1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(retorno1)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout temasLayout = new javax.swing.GroupLayout(temas);
        temas.setLayout(temasLayout);
        temasLayout.setHorizontalGroup(
            temasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tema6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(temasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tema2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(temasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tema3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(temasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(temasLayout.createSequentialGroup()
                    .addComponent(tema4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(temasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(temasLayout.createSequentialGroup()
                    .addComponent(tema5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(temasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tema1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        temasLayout.setVerticalGroup(
            temasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tema6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(temasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tema2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(temasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tema3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(temasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tema4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(temasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tema5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(temasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tema1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fundoAngular2.setBackground(new java.awt.Color(231, 231, 231));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/angular.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/tourofheroes.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/tourofheroesimg.png"))); // NOI18N

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/acesseoprojeto.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fundoAngular2Layout = new javax.swing.GroupLayout(fundoAngular2);
        fundoAngular2.setLayout(fundoAngular2Layout);
        fundoAngular2Layout.setHorizontalGroup(
            fundoAngular2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoAngular2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(fundoAngular2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addGroup(fundoAngular2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(fundoAngular2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        fundoAngular2Layout.setVerticalGroup(
            fundoAngular2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoAngular2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel14)
                .addGroup(fundoAngular2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoAngular2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundoAngular2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel17)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        fundoTdS.setBackground(new java.awt.Color(231, 231, 231));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/testesdesoftware.png"))); // NOI18N

        botaoTema1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/tema1.png"))); // NOI18N
        botaoTema1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoTema1MouseClicked(evt);
            }
        });

        botaoTema2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/tema2.png"))); // NOI18N
        botaoTema2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoTema2MouseClicked(evt);
            }
        });

        botaoTema3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/tema3.png"))); // NOI18N
        botaoTema3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoTema3MouseClicked(evt);
            }
        });

        botaoTema4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/tema4.png"))); // NOI18N
        botaoTema4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoTema4MouseClicked(evt);
            }
        });

        botaoTema5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/tema5.png"))); // NOI18N
        botaoTema5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoTema5MouseClicked(evt);
            }
        });

        botaoTema6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/tema6.png"))); // NOI18N
        botaoTema6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoTema6MouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/atvpraticas.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fundoTdSLayout = new javax.swing.GroupLayout(fundoTdS);
        fundoTdS.setLayout(fundoTdSLayout);
        fundoTdSLayout.setHorizontalGroup(
            fundoTdSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoTdSLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(fundoTdSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addGroup(fundoTdSLayout.createSequentialGroup()
                        .addGroup(fundoTdSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(fundoTdSLayout.createSequentialGroup()
                                .addComponent(botaoTema4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoTema5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(fundoTdSLayout.createSequentialGroup()
                                .addComponent(botaoTema1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoTema2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fundoTdSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoTema3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoTema6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        fundoTdSLayout.setVerticalGroup(
            fundoTdSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoTdSLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(fundoTdSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoTema1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoTema2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoTema3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundoTdSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoTema4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoTema5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoTema6))
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        fundoScrum.setBackground(new java.awt.Color(231, 231, 231));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/scrum.png"))); // NOI18N

        javax.swing.GroupLayout fundoScrumLayout = new javax.swing.GroupLayout(fundoScrum);
        fundoScrum.setLayout(fundoScrumLayout);
        fundoScrumLayout.setHorizontalGroup(
            fundoScrumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoScrumLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        fundoScrumLayout.setVerticalGroup(
            fundoScrumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoScrumLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel5)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        fundoAnalytics.setBackground(new java.awt.Color(231, 231, 231));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/analytics.png"))); // NOI18N

        javax.swing.GroupLayout fundoAnalyticsLayout = new javax.swing.GroupLayout(fundoAnalytics);
        fundoAnalytics.setLayout(fundoAnalyticsLayout);
        fundoAnalyticsLayout.setHorizontalGroup(
            fundoAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoAnalyticsLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        fundoAnalyticsLayout.setVerticalGroup(
            fundoAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoAnalyticsLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        fundoHome.setBackground(new java.awt.Color(231, 231, 231));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages/home.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bem-vindo!");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(99, 99, 99));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Clique nos menus laterais para navegar pelas páginas");

        javax.swing.GroupLayout fundoHomeLayout = new javax.swing.GroupLayout(fundoHome);
        fundoHome.setLayout(fundoHomeLayout);
        fundoHomeLayout.setHorizontalGroup(
            fundoHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoHomeLayout.createSequentialGroup()
                .addGroup(fundoHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fundoHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fundoHomeLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(fundoHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))))
                .addContainerGap())
        );
        fundoHomeLayout.setVerticalGroup(
            fundoHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoHomeLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout fundoAngularLayout = new javax.swing.GroupLayout(fundoAngular);
        fundoAngular.setLayout(fundoAngularLayout);
        fundoAngularLayout.setHorizontalGroup(
            fundoAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoAngularLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fundoHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fundoAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoAngularLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fundoAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(fundoAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoAngularLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fundoScrum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(fundoAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoAngularLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fundoTdS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(fundoAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoAngularLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fundoAngular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(fundoAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoAngularLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(temas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        fundoAngularLayout.setVerticalGroup(
            fundoAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fundoAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fundoAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fundoAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fundoScrum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fundoAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fundoTdS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fundoAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fundoAngular2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fundoAngularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(temas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 640, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 260, Short.MAX_VALUE)
                    .addComponent(fundoAngular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fundoAngular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseClicked
        fundoHome.setVisible(true);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(false);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(false);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonHomeMouseClicked

    private void buttonAnalyticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAnalyticsMouseClicked
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(true);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(false);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(false);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAnalyticsMouseClicked

    private void buttonScrumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonScrumMouseClicked
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(true);
        fundoTdS.setVisible(false);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(false);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonScrumMouseClicked

    private void buttonTdSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTdSMouseClicked
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(true);
        fundoAngular2.setVisible(false);
        fundoAngular.setVisible(true);
        temas.setVisible(false);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTdSMouseClicked

    private void buttonAngularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAngularMouseClicked
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(false);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(true);
        temas.setVisible(false);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAngularMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        try{
            if (Desktop.isDesktopSupported()){
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)){
                    desktop.browse(new URI("https://angular-ivy-gq7gvq.stackblitz.io/"));
                }
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void botaoTema1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTema1MouseClicked
        // TODO add your handling code here:
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(false);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(true);
        tema1.setVisible(true);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);
    }//GEN-LAST:event_botaoTema1MouseClicked

    private void botaoTema2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTema2MouseClicked
        // TODO add your handling code here:
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(false);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(true);
        tema1.setVisible(false);
        tema2.setVisible(true);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);        
    }//GEN-LAST:event_botaoTema2MouseClicked

    private void botaoTema3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTema3MouseClicked
        // TODO add your handling code here:
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(false);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(true);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(true);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);
    }//GEN-LAST:event_botaoTema3MouseClicked

    private void botaoTema4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTema4MouseClicked
        // TODO add your handling code here:
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(false);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(true);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(true);
        tema5.setVisible(false);
        tema6.setVisible(false);
    }//GEN-LAST:event_botaoTema4MouseClicked

    private void botaoTema5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTema5MouseClicked
        // TODO add your handling code here:
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(false);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(true);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(true);
        tema6.setVisible(false);
    }//GEN-LAST:event_botaoTema5MouseClicked

    private void botaoTema6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTema6MouseClicked
        // TODO add your handling code here:
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(false);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(true);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(true);
    }//GEN-LAST:event_botaoTema6MouseClicked

    private void retorno1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retorno1MouseClicked
        // TODO add your handling code here:
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(true);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(false);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);
    }//GEN-LAST:event_retorno1MouseClicked

    private void retorno2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retorno2MouseClicked
        // TODO add your handling code here:
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(true);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(false);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);
    }//GEN-LAST:event_retorno2MouseClicked

    private void retorno3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retorno3MouseClicked
        // TODO add your handling code here:
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(true);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(false);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);
    }//GEN-LAST:event_retorno3MouseClicked

    private void retorno4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retorno4MouseClicked
        // TODO add your handling code here:
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(true);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(false);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);
    }//GEN-LAST:event_retorno4MouseClicked

    private void retorno5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retorno5MouseClicked
        // TODO add your handling code here:
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(true);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(false);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);
    }//GEN-LAST:event_retorno5MouseClicked

    private void retorno6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retorno6MouseClicked
        // TODO add your handling code here:
        fundoHome.setVisible(false);
        fundoAnalytics.setVisible(false);
        fundoScrum.setVisible(false);
        fundoTdS.setVisible(true);
        fundoAngular.setVisible(true);
        fundoAngular2.setVisible(false);
        temas.setVisible(false);
        tema1.setVisible(false);
        tema2.setVisible(false);
        tema3.setVisible(false);
        tema4.setVisible(false);
        tema5.setVisible(false);
        tema6.setVisible(false);
    }//GEN-LAST:event_retorno6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        try{
            if (Desktop.isDesktopSupported()){
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)){
                    desktop.browse(new URI("https://drive.google.com/file/d/1jnWKctTpYj1PdYzWLF-uOYBVkvZRQoO9/view?usp=sharing"));
                }
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        try{
            if (Desktop.isDesktopSupported()){
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)){
                    desktop.browse(new URI("https://drive.google.com/file/d/1vNYnlol2AOLhouB9nVDknAH-ciyRuAN5/view?usp=sharing"));
                }
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        try{
            if (Desktop.isDesktopSupported()){
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)){
                    desktop.browse(new URI("https://drive.google.com/file/d/1GIrbSOJlWmPzmbUQv-_JliUKgWbFfkTc/view?usp=sharing"));
                }
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        try{
            if (Desktop.isDesktopSupported()){
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)){
                    desktop.browse(new URI("https://drive.google.com/file/d/1Gjl395Bf2L_vQfdMKPXN5TXSlO---bdb/view?usp=sharing"));
                }
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        try{
            if (Desktop.isDesktopSupported()){
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)){
                    desktop.browse(new URI("https://drive.google.com/file/d/1BEV2EWxNC9Ybc1hLNshCDzM9GIU2NOKe/view?usp=sharing"));
                }
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        try{
            if (Desktop.isDesktopSupported()){
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)){
                    desktop.browse(new URI("https://drive.google.com/file/d/1bzqqImFpYW4ejhryOa5-e5DI_o-FOqnQ/view?usp=sharing"));
                }
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        try{
            if (Desktop.isDesktopSupported()){
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)){
                    desktop.browse(new URI("https://drive.google.com/drive/folders/1qFU31ASMQX-3m7AmRxezEOABT5iphhxw?usp=sharing"));
                }
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuV2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel analytics;
    private javax.swing.JLabel angular;
    private javax.swing.JPanel barraLateral;
    private javax.swing.JLabel botaoTema1;
    private javax.swing.JLabel botaoTema2;
    private javax.swing.JLabel botaoTema3;
    private javax.swing.JLabel botaoTema4;
    private javax.swing.JLabel botaoTema5;
    private javax.swing.JLabel botaoTema6;
    private javax.swing.JPanel buttonAnalytics;
    private javax.swing.JPanel buttonAngular;
    private javax.swing.JPanel buttonHome;
    private javax.swing.JPanel buttonScrum;
    private javax.swing.JPanel buttonTdS;
    private javax.swing.JPanel fundoAnalytics;
    private javax.swing.JPanel fundoAngular;
    private javax.swing.JPanel fundoAngular2;
    private javax.swing.JPanel fundoHome;
    private javax.swing.JPanel fundoScrum;
    private javax.swing.JPanel fundoTdS;
    private javax.swing.JLabel home;
    private javax.swing.JLabel iconAnalytics;
    private javax.swing.JLabel iconAngular;
    private javax.swing.JLabel iconHome;
    private javax.swing.JLabel iconScrum;
    private javax.swing.JLabel iconTdS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel retorno1;
    private javax.swing.JLabel retorno2;
    private javax.swing.JLabel retorno3;
    private javax.swing.JLabel retorno4;
    private javax.swing.JLabel retorno5;
    private javax.swing.JLabel retorno6;
    private javax.swing.JLabel scrum;
    private javax.swing.JPanel tema1;
    private javax.swing.JPanel tema2;
    private javax.swing.JPanel tema3;
    private javax.swing.JPanel tema4;
    private javax.swing.JPanel tema5;
    private javax.swing.JPanel tema6;
    private javax.swing.JPanel temas;
    private javax.swing.JLabel testesDeSoftware;
    private javax.swing.JPanel yellowBar;
    private javax.swing.JPanel yellowBar2;
    private javax.swing.JPanel yellowBar4;
    private javax.swing.JPanel yellowBar5;
    private javax.swing.JPanel yellowBar7;
    // End of variables declaration//GEN-END:variables
}
